[package]
name = "ydcv-rs"
description = "A rust version of YouDao Console Version"
repository = "https://github.com/farseerfc/ydcv-rs"
readme = "README.md"
license = "GPL-2.0"
version = "0.3.6"
authors = ["Jiachen Yang <farseerfc@gmail.com>"]

[dependencies]
structopt = "0.0.3"
structopt-derive = "0.0.3"
rustc-serialize = "0.3"
env_logger = "0.4"
rustyline = "1.0"
log = "0.3"
lazy_static = "0.2"
isatty = "0.1"
reqwest = "0.5"
x11-clipboard = "0.1"

[dependencies.notify-rust]
version = "3.0"
optional = true

[features]
default = ["notify-rust"]
