[package]
name = "ydcv-rs"
description = "A rust version of YouDao Console Version"
repository = "https://github.com/farseerfc/ydcv-rs"
readme = "README.md"
license = "GPL-2.0"
version = "0.3.3"
authors = ["Jiachen Yang <farseerfc@gmail.com>"]

[dependencies]
rustc-serialize = "0.3"
env_logger = "0.3"
rustyline = "1.0"
getopts = "0.2"
libc = "0.2"
log = "0.3"
url = "0.5"
hyper = "0.9"

[dependencies.notify-rust]
version = "3.0"
optional = true

[features]
default = ["notify-rust"]

