[package]
name = "ydcv-rs"
version = "0.2.1"
authors = ["Jiachen Yang <jc-yang@ist.osaka-u.ac.jp>"]

[dependencies]
rustc-serialize = "*"
log = "*"
env_logger = "*"
getopts = "*"
readline = "*"
libc = "*"
url = "*"

[dependencies.notify-rust]
version = "*"
optional = true

[dependencies.curl]
version = "*"
optional = true

[dependencies.hyper]
version = "*"
optional = true

[features]
default = ["curl", "notify-rust"]

