[package]
name = "ydcv-rs"
version = "0.2.0"
authors = ["Jiachen Yang <jc-yang@ist.osaka-u.ac.jp>"]

[dependencies]
rustc-serialize = "*"
log = "*"
env_logger = "*"
getopts = "*"
readline = "*"
notify-rust = "*"
libc = "*"
url = "*"

[dependencies.curl]
version = "*"
optional = true

[dependencies.hyper]
version = "*"
optional = true

[features]
default = ["use_curl"]
use_curl = ["curl"]
use_hyper = ["hyper"]